### PR TITLE
MNT: compatibility with newer packaging

### LINKED ISSUE #27: LegacyVersion has been removed from packaging.version
* docs_versions_menu version: latest (0.5.0+dev)
* Python version: 3.10
* Operating System: linux

### Description

`LegacyVersion` was removed. Trying to use it raises an error:
```
Extension error:
Could not import extension docs_versions_menu (exception: cannot import name 'LegacyVersion' from 'packaging.version' (/[...]/site-packages/packaging/version.py))
ERROR: InvocationError for command /[...]/bin/sphinx-build -M html . _build (exited with code 2)
```

### What I Did

https://github.com/awoimbee/docs_versions_menu/commit/d6063fd0ccf26bfce6a9fcf07c9251863d16ec3a

### PR DESCRIPTION
**Pull request by ZLLentz**
I dug into this a bit because newer versions of `black` and `conda` require `packaging>=22.0`.

Following recommendations here: https://github.com/pypa/packaging/issues/631#issuecomment-1343479721
The simplest way to support all versions of packaging is to use the `Version` class directly instead of the `parse` function.

`parse` used to return `Version` or `LegacyVersion` depending on if it received a valid version string, but now it raises `InvalidVersion` instead if the version string is invalid. If we add a try/except around `parse` then you'll be compatible with `packaging>=22` but lose compatibility with `packaging<22`. Instead, switching to the `Version` class directly has the same exception raising behavior in all versions of `packaging`, including the latest.

This seemed like an appropriate fix here because this library only uses `LegacyVersion` as an indicator that something is a branch rather than a version, so its absence doesn't seem like much of a problem.

closes #27

### CODE REVIEW

**Comment by goerz** [comment]
Looks like it should work in principle, and I'd be happy to merge if you can make the tests pass.

You'll also have to pin `black < 23`.

**Comment by goerz** [comment]
It's not going to be that easy… There are several other places where `parse_version` is called, and I really depend on the old behavior. The easiest fix is probably to backport the entire old `parse_version` function and the `LegacyVersion` type (or something that behaves equivalently) into the package.

**Comment by ZLLentz** [comment]
I didn't realize you were using `parse_version` elsewhere, that's my bad.

Maybe the easiest thing to do is to use https://pypi.org/project/packvers/ which I think is just a forked/vendored version of packaging at 21.3, or backport/vendor it yourself if you prefer.

**Comment by goerz** [comment]
I'm going to look into this in #32

**Comment by ZLLentz** [comment]
Thank you for moving ahead with this!

**Pull request closed without merging**
